-- AlterEnum: add kiosk & fleet-control command types for the unified RMLauncher agent.
ALTER TYPE "CommandType" ADD VALUE 'REBOOT';
ALTER TYPE "CommandType" ADD VALUE 'REAPPLY_POLICIES';
ALTER TYPE "CommandType" ADD VALUE 'ENTER_KIOSK';
ALTER TYPE "CommandType" ADD VALUE 'EXIT_KIOSK';
ALTER TYPE "CommandType" ADD VALUE 'SET_CAMERA_DISABLED';
ALTER TYPE "CommandType" ADD VALUE 'SET_STATUS_BAR_DISABLED';
ALTER TYPE "CommandType" ADD VALUE 'SET_KEYGUARD_DISABLED';
ALTER TYPE "CommandType" ADD VALUE 'SET_WHITELIST';
ALTER TYPE "CommandType" ADD VALUE 'SET_APP_HIDDEN';
ALTER TYPE "CommandType" ADD VALUE 'ENABLE_SYSTEM_APP';
ALTER TYPE "CommandType" ADD VALUE 'INSTALL_APK';
